<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591;1570</NoWarn>
		<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
		<RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    </PropertyGroup>

    <ItemGroup>
        <!-- Exclude test project directory -->
        <Compile Remove="CloudCore.Tests/**" />
        <EmbeddedResource Remove="CloudCore.Tests/**" />
        <None Remove="CloudCore.Tests/**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="NaturalSort.Extension" Version="4.4.0" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
        <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="logs\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="Common\EmailTemplates\ResetPassword.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Common\EmailTemplates\VerifyEmail.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
</Project>
